# Generated by Django 2.0 on 2019-05-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleavingmessage',
            name='message_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userleavingmessage',
            name='message_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
