# Generated by Django 2.0 on 2019-05-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20190520_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userleavingmessage',
            old_name='message_content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='userleavingmessage',
            old_name='message_title',
            new_name='subject',
        ),
    ]
