# Generated by Django 2.0 on 2019-05-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='send_time',
            field=models.DateTimeField(auto_now=True, verbose_name='发送时间'),
        ),
    ]
